### ISSUE TITLE
how do i disable nsfw content on that?

### ISSUE THREAD

**Issue by Asplushii** [ShivaBhattacharjee/AnimeTrix#10]
i started hosting the website on my own machine for fun and i want to remove nsfw content from the website if possible

**Comment by ShivaBhattacharjee** [comment]
> i started hosting the website on my own machine for fun and i want to remove nsfw content from the website if possible

**You can disable ecchi genre on the genre section however NSFW content will still be visible if searched for it  and there's nothing I can do about it **

**Comment by ShivaBhattacharjee** [comment]
I would like to inform you that we have removed nsfw content from our site by migrating  api
