### ISSUE TITLE
Ability to switch between sub and dub?

### ISSUE THREAD

**Issue by ILikeW** [ShivaBhattacharjee/AnimeTrix#35]
Not sure if already has this ability but i would like to switch between sub and dub anime.

**Comment by ShivaBhattacharjee** [comment]
Yeah i am working on this feature it will be out in few days

**Comment by ILikeW** [comment]
quick reply? love it, noted.

**Comment by ILikeW** [comment]
so the people who already have the code, like how would they update it?

**Comment by ShivaBhattacharjee** [comment]
> so the people who already have the code, like how would they update it?

Well you can fork my repo (ps: i will release the dub anime update this week) currently i added pwa and removed some bloated code to improve performance

**Comment by ILikeW** [comment]
got u

**Comment by ShivaBhattacharjee** [comment]
I have added this feature clear cache of your browser to see the changes or pull the latest changes in your local machine
