### ISSUE TITLE
project is keep getting faild on vercel 

### ISSUE THREAD

**Issue by gusfing** [ShivaBhattacharjee/AnimeTrix#57]
**Describe the bug**
A clear and concise description of what the bug is. run command is showing error 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ShivaBhattacharjee** [comment]
Bro atleast explain the bug instead of copy pasting template
