### ISSUE TITLE
Not able to deploy on vercel

### ISSUE THREAD

**Issue by PranavXDYT** [ShivaBhattacharjee/AnimeTrix#59]
I am getting error while deploying on vercel please guide me which build and install command should I input to deploy on vercel.
![Screenshot_2023-05-28-11-01-22-40_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ShivaBhattacharjee/AnimeTrix/assets/86994182/a49199d3-8377-4a2c-aed8-d3c7fc9bf611)
![Screenshot_2023-05-28-11-01-13-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ShivaBhattacharjee/AnimeTrix/assets/86994182/ecfa0ff7-5167-4805-8788-7b2a76e1940b)

**Comment by ShivaBhattacharjee** [comment]
Go to settings and  change npm install to npm install --force
